config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :people do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email, :avatar
      post :bulk_edit, :bulk_update, :send_mails
      delete :bulk_destroy
      get :skills
      get :foreign_languages
      get :hobbies
    end
end

resources :people_settings do
  collection do
    get :autocomplete_for_user
  end
end
# match "people_settings/:action" => "people_settings"

app/models/person.rb
class Person < ActiveRecord::Base
  unloadable
  self.inheritance_column = :_type_disabled

  include Redmine::SafeAttributes
  acts_as_attachable_global
  acts_as_taggable_on :hobbies, :skills, :foreign_languages

  belongs_to :company

  STATUS_ANONYMOUS = 0
  GENDERS = [[l(:label_people_male), 0], [l(:label_people_female), 1]]
  CONTACT_TYPES = %W[internal external]
  SEARCH_ATTRS = %w[first_name last_name middle_name nickname email]
  EDUCATION_VALUES = %w[higher incomplete_higher higher_student specialized_secondary seondary]

  scope :logged_with_status, lambda { |arg| joins{ user.outer }.where { ((user.status != STATUS_ANONYMOUS) & (user.status == arg)) | ((contact_type == 'internal') & (user_id == nil)) | (contact_type == 'external')} }
  scope :in_group, lambda {|group|
    group_id = group.is_a?(Group) ? group.id : group.to_i
    { :conditions => ["#{User.table_name}.id IN (SELECT gu.user_id FROM #{table_name_prefix}groups_users#{table_name_suffix} gu WHERE gu.group_id = ?)", group_id] }
  }
  scope :search_by_name, lambda {|search| where { SEARCH_ATTRS.map { |attr| (__send__(attr) =~ "%#{search}%") }.inject(&:|)} }

  belongs_to :user
  belongs_to :default_role, :class_name => 'Role'
  has_many :memberships, :through => :user
  has_one :avatar, :class_name => "Attachment", :as  => :container, :conditions => "#{Attachment.table_name}.description = 'avatar'", :dependent => :destroy

  validates_presence_of :nickname
  validates_presence_of :email, :if => Proc.new { |person| person.external? }
  validates_uniqueness_of :email, :if => Proc.new { |person| !person.email.blank? }, :case_sensitive => false
  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :allow_blank => true

  safe_attributes 'first_name',
                  'middle_name',
                  'last_name',
                  'email',
                  'company',
                  'job_title',
                  'avatar',
                  'nickname',
                  'gender',
                  'birthday',
                  'address',
                  'mobile_phone',
                  'landline_phone',
                  'skype',
                  'github',
                  'facebook',
                  'twitter',
                  'linkedin',
                  'foursquare',
                  'background',
                  'contact_type',
                  'default_role_id',
                  'skill_list',
                  'foreign_language_list',
                  'hobby_list'


  def mobile_phones
    @mobile_phones || self.mobile_phone ? self.mobile_phone.split( /, */) : []
  end

  def landline_phones
    @landline_phones || self.landline_phone ? self.landline_phone.split( /, */) : []
  end

  def internal?
    self.contact_type == 'internal'
  end

  def external?
    self.contact_type == 'external'
  end

  def email
    external? ? self.read_attribute(:email) : self.user.try(:mail)
  end

  def first_name
    external? ? self.read_attribute(:first_name) : self.user.try(:firstname)
  end

  def last_name
    external? ? self.read_attribute(:last_name) : self.user.try(:lastname)
  end

  def self.available_users
    ids = Person.pluck(:user_id).uniq
    User.where { (id << ids) & (type == 'User') }
  end

  def self.available_roles
    Role.all
  end

  def next_birthday
    return if birthday.blank?
    year = Date.today.year
    mmdd = birthday.strftime('%m%d')
    year += 1 if mmdd < Date.today.strftime('%m%d')
    mmdd = '0301' if mmdd == '0229' && !Date.parse("#{year}0101").leap?
    return Date.parse("#{year}#{mmdd}")
  end

  def self.next_birthdays(limit = 10)
    Person.where("people.birthday IS NOT NULL").sort_by(&:next_birthday).first(limit)
  end

  def age
    return nil if birthday.blank?
    now = Time.now
    age = now.year - birthday.year - (birthday.to_time.change(:year => now.year) > now ? 1 : 0)
  end

  def editable_by?(usr, prj=nil)
    true
    # usr && (usr.allowed_to?(:edit_people, prj) || (self.author == usr && usr.allowed_to?(:edit_own_invoices, prj)))
    # usr && usr.logged? && (usr.allowed_to?(:edit_notes, project) || (self.author == usr && usr.allowed_to?(:edit_own_notes, project)))
  end

  def visible?(usr=nil)
    true
  end

  def attachments_visible?(user=User.current)
    true
  end

  def project
    if self.respond_to?(:user) && user
      user.project
    else
      Project.new
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  unloadable

  Mime::Type.register "text/x-vcard", :vcf

  before_filter :find_person, :only => [:show, :edit, :update, :destroy, :edit_membership, :destroy_membership]
  before_filter :authorize_people, :except => [:avatar, :context_menu, :skills, :foreign_languages, :hobbies]
  before_filter :bulk_find_people, :only => [:context_menu, :bulk_destroy]
  before_filter :load_job_titles, only: [:new, :edit]

  include PeopleHelper

  def index
  	@people = find_people
    @groups = Group.all.sort
    @next_birthdays = Person.next_birthdays

    respond_to do |format|
      format.html {render :partial => 'list_excerpt', :layout => false if request.xhr?}
    end
  end

  def skills
    q = params[:q]
    @tags = Person.skill_counts.where { tags.name =~ "%#{q}%" }
    respond_tags
  end

  def foreign_languages
    q = params[:q]
    @tags = Person.foreign_language_counts.where { tags.name =~ "%#{q}%" }
    respond_tags
  end

  def hobbies
    q = params[:q]
    @tags = Person.hobby_counts.where { tags.name =~ "%#{q}%" }
    respond_tags
  end

  def show
    # @person.roles = Role.new(:permissions => [:download_attachments])
    events = Redmine::Activity::Fetcher.new(User.current, :author => @person.user).events(nil, nil, :limit => 10)
    @events_by_day = events.group_by(&:event_date)
    @person_attachments = @person.attachments.select{|a| a != @person.avatar}
    @memberships = @person.memberships.all(:conditions => Project.visible_condition(User.current))
    respond_to do |format|
      format.html
      format.vcf { send_data(person_to_vcard(@person), :filename => "#{@person.nickname}.vcf", :type => 'text/x-vcard;', :disposition => 'attachment') }
    end
  end

  def edit
    @auth_sources = AuthSource.find(:all)
    @membership ||= Member.new
  end

  def new
    @person = Person.new
    @auth_sources = AuthSource.find(:all)
  end

  def update
    (render_403; return false) unless @person.editable_by?(User.current)
    if @person.update_attributes(params[:person])
      @person.user_id = params[:person][:user_id] if params[:person]
      @person.save!
      flash[:notice] = l(:notice_successful_update)
      attach_avatar
      attachments = Attachment.attach_files(@person, params[:attachments])
      render_attachment_warning_if_needed(@person)
      respond_to do |format|
        format.html { redirect_to :action => "show", :id => @person }
        format.api  { head :ok }
      end
    else
      respond_to do |format|
        format.html { render :action => "edit"}
        format.api  { render_validation_errors(@person) }
      end
    end
  end

  def create
    @person  = Person.new
    @person.safe_attributes = params[:person]
    @person.user_id = params[:person][:user_id] if params[:person]
    if @person.save
      attach_avatar

      respond_to do |format|
        format.html {
          flash[:notice] = l(:notice_successful_create, :id => view_context.link_to(@person.nickname, person_path(@person)))
          redirect_to(params[:continue] ?
            {:controller => 'people', :action => 'new'} :
            {:controller => 'people', :action => 'show', :id => @person}
          )
        }
        format.api  { render :action => 'show', :status => :created, :location => person_url(@person) }
      end
    else
      respond_to do |format|
        format.html { render :action => 'new' }
        format.api  { render_validation_errors(@person) }
      end
    end
  end

  def destroy
    @person.destroy

    respond_to do |format|
      format.html {
        flash[:notice] = l(:notice_successful_delete, :id => view_context.link_to(@person.nickname, person_path(@person)))
        redirect_to({:controller => 'people', :action => 'index'})
      }
    end
  end

  def bulk_destroy
    @people.map(&:destroy)

    respond_to do |format|
      format.html {
        flash[:notice] = l(:notice_successful_delete)
        redirect_to({:controller => 'people', :action => 'index'})
      }
    end
  end

  def avatar
    attachment = Attachment.find(params[:id])
    # debugger
    if attachment.readable? && attachment.thumbnailable?
      # images are sent inline
      if defined?(RedmineContacts::Thumbnail) == 'constant'
        target = File.join(attachment.class.thumbnails_storage_path, "#{attachment.id}_#{attachment.digest}_#{params[:size]}.thumb")
        thumbnail = RedmineContacts::Thumbnail.generate(attachment.diskfile, target, params[:size])
      elsif Redmine::Thumbnail.convert_available?
        thumbnail = attachment.thumbnail(:size => params[:size])
      else
        thumbnail = attachment
      end

      if stale?(:etag => attachment.digest)
        send_file (thumbnail || attachment.diskfile), :filename => (request.env['HTTP_USER_AGENT'] =~ %r{MSIE} ? ERB::Util.url_encode(attachment.filename) : attachment.filename),
                                        :type => detect_content_type(attachment),
                                        :disposition => 'inline'
      end

    # attachment_file = attachment
    # if attachment.thumbnailumbnailable? && thumbnail = attachment.thumbnail(:size => params[:size])
    #   if stale?(:etag => thumbnail)
    #     send_file thumbnail,
    #       :filename => (request.env['HTTP_USER_AGENT'] =~ %r{MSIE} ? ERB::Util.url_encode(attachment.filename) : attachment.filename),
    #       :type => detect_content_type(attachment),
    #       :disposition => 'inline'
    #   end
    # else
    #   # No thumbnail for the attachment or thumbnail could not be created
    #   render :nothing => true, :status => 404
    end

  rescue ActiveRecord::RecordNotFound
    render :nothing => true, :status => 404
  end

  def context_menu
    @person = @people.first if (@people.size == 1)
    @can = {:edit =>  @people.collect{|c| User.current.allowed_people_to?(:edit_people, @person)}.inject{|memo,d| memo && d},
            :delete =>  @people.collect{|c| User.current.allowed_people_to?(:delete_people, @person)}.inject{|memo,d| memo && d}
            }

    # @back = back_url
    render :layout => false
  end

private
  def authorize_people
    allowed = case params[:action].to_s
      when "create", "new"
        User.current.allowed_people_to?(:add_people, @person)
      when "update", "edit"
        User.current.allowed_people_to?(:edit_people, @person)
      when "destroy", "bulk_destroy"
        User.current.allowed_people_to?(:delete_people, @person)
      when "index", "show"
        User.current.allowed_people_to?(:view_people, @person)
      else
        false
      end

    if allowed
      true
    else
      deny_access
    end
  end

  def attach_avatar
    if params[:person_avatar]
      params[:person_avatar][:description] = 'avatar'
      @person.avatar.destroy if @person.avatar
      Attachment.attach_files(@person, {"1" => params[:person_avatar]})
      render_attachment_warning_if_needed(@person)
    end
  end

  def detect_content_type(attachment)
    content_type = attachment.content_type
    if content_type.blank?
      content_type = Redmine::MimeType.of(attachment.filename)
    end
    content_type.to_s
  end

  def find_person
    @person = Person.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_people(pages=true)
    # scope = scope.scoped(:conditions => ["#{Person.table_name}.status_id = ?", params[:status_id]]) if (!params[:status_id].blank? && params[:status_id] != "o" && params[:status_id] != "d")
    @status = params[:status] || 1
    scope = Person.logged_with_status(@status)
    scope = scope.search_by_name(params[:name]) if params[:name].present?
    scope = scope.in_group(params[:group_id]) if params[:group_id].present?

    @people_count = scope.count
    @group = Group.find(params[:group_id]) if params[:group_id].present?
    if pages
      @limit =  per_page_option
      @people_pages = Paginator.new(self, @people_count,  @limit, params[:page])
      @offset = @people_pages.current.offset

      scope = scope.scoped :limit  => @limit, :offset => @offset
      @people = scope

      fake_name = @people.first.nickname if @people.length > 0 #without this patch paging does not work
    end

    scope
  end

  def bulk_find_people
    @people = Person.find_all_by_id(params[:id] || params[:ids])

    raise ActiveRecord::RecordNotFound if @people.empty?
    if @people.detect {|person| !person.visible?}
      deny_access
      return
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def respond_tags
    respond_to do |format|
      format.json { render json: @tags.collect{ |t| {:id => t.name, :name => t.name } } }
    end
  end

  def load_job_titles
    @job_titles = Person.pluck(:job_title).compact.uniq
  end
end

app/helpers/people_helper.rb
module PeopleHelper

  def birthday_date(person)
    if person.birthday.day == Date.today.day && person.birthday.month == Date.today.month
       "#{l(:label_today).capitalize} (#{person.age + 1})"
    else
      "#{person.birthday.day} #{t('date.month_names')[person.birthday.month]} (#{person.age + 1})"
    end
  end

  def person_to_vcard(person)
    require 'vpim/vcard'

    card = Vpim::Vcard::Maker.make2 do |maker|

      maker.add_name do |name|
        name.prefix = ''
        name.given = person.first_name.to_s
        name.family = person.last_name.to_s
        name.additional = person.middle_name.to_s
      end

      maker.add_addr do |addr|
        addr.preferred = true
        addr.street = person.address.to_s.gsub("\r\n"," ").gsub("\n"," ")
      end

      maker.title = person.job_title.to_s
      maker.org = person.company.to_s
      maker.birthday = person.birthday.to_date unless person.birthday.blank?
      maker.add_note(person.background.to_s.gsub("\r\n"," ").gsub("\n", ' '))

      # maker.add_url(person.website.to_s)

      person.mobile_phones.each { |phone| maker.add_tel(phone) }
      person.landline_phones.each { |phone| maker.add_tel(phone) }

      email = person.external? ? person.email : person.user.mail
      maker.add_email(email)
    end
    avatar = person.avatar
    card = card.encode.sub("END:VCARD", "PHOTO;BASE64:" + "\n " + [File.open(avatar.diskfile).read].pack('m').to_s.gsub(/[ \n]/, '').scan(/.{1,76}/).join("\n ") + "\nEND:VCARD") if avatar && avatar.readable?

    card.to_s

  end

  def icon(type)
    "<i class=\"icon-#{type}\"></i> ".html_safe
  end
end

app/views/people/_activity.html.erb
<% unless @events_by_day.empty? %>
  <div id="activity">
    <% @events_by_day.keys.sort.reverse.each do |day| %>
    <h4><%= format_activity_day(day) %></h4>
    <dl>
    <% @events_by_day[day].sort {|x,y| y.event_datetime <=> x.event_datetime }.each do |e| -%>
      <dt class="<%= e.event_type %>">
      <span class="time"><%= format_time(e.event_datetime, false) %></span>
      <%= content_tag('span', h(e.project), :class => 'project') %>
      <%= link_to format_activity_title(e.event_title), e.event_url %></dt>
      <dd><span class="description"><%= format_activity_description(e.event_description) %></span></dd>
    <% end -%>
    </dl>
    <% end -%>
  </div>
  <%= link_to l(:label_activity) + " \xc2\xbb", :controller => 'activities',
                :action => 'index', :id => nil, :user_id => @person.user,
                :from => @events_by_day.keys.first if @person.user %>
<% end -%>

app/views/people/_attachments.html.erb
<div id="person_files">
  <div class="contextual">     
    <%= link_to l(:button_add), {}, :onclick => "$('#add_attachment_form').show(); $('#add_attachment_link').hide(); return false;", :class => 'icon icon-add', :id => 'add_attachment_link' if User.current.allowed_people_to?(:edit_people, @person) %> 
  </div>
  <%= labelled_form_for :person, @person, 
                               :url => {:action => 'update', :id => @person}, 
                               :html => { :multipart => true, :method => :put, :id => "add_attachment_form", :style => "display:none;" } do |f|  %>
      <fieldset>
        <%= error_messages_for 'person' %>

        <p><%=l(:label_attachment_plural)%><br /><%= render :partial => 'attachments/form', :locals => {:container => @person} %></p>
        <%= submit_tag l(:button_save) -%>   
        <%= link_to l(:button_cancel), {}, :onclick => "$('#add_attachment_form').hide(); $('#add_attachment_link').show(); return false;"  %>  
      </fieldset>
  <% end -%>
  <%= render :partial => 'attachments/links', :locals => {:attachments => @person_attachments, :options  => {:author => true, :deletable => :true}, :thumbnails => Setting.thumbnails_enabled?} %>
</div>

app/views/people/_attributes.html.erb
<div id="attributes">
  <h3><%= l(:label_people_person) %></h3>
  <%= call_hook(:view_persons_sidebar_attributes_top) %>
  <% if @person.external? %>
    <h4><%= @person.first_name %> <%= @person.middle_name %> <%= @person.last_name %></h4>
    <%= icon('envelope') %> <%= mail_to @person.email %>
  <% end %>
  <% if !@person.job_title.blank? %>
    <%= l(:field_people_job_title) %>: <%= @person.job_title %>
  <% end %>
  <ul>
    <li>
      <% unless @person.address.blank? %>
        <%= icon('map-marker') %>
        <%= link_to @person.address, "http://maps.google.com/maps?f=q&q=#{h @person.address.gsub("\r\n"," ").gsub("\n"," ")}+(#{h @person.nickname})&ie=UTF8&om=1"%>
      <% end %>
    </li>
    <% @person.mobile_phones.each do |phone| %>
      <li>
        <%= icon('mobile-phone') %>
        <%= h phone %>
      </li>
    <% end %>
    <% @person.landline_phones.each do |phone| %>
      <li>
        <%= icon('phone') %>
        <%= h phone %>
      </li>
    <% end %>
    <% unless @person.skype.blank? %>
      <li>
        <%= icon('skype') %>
        <%= link_to @person.skype, "skype:#{@person.skype}?call" %>
      </li>
    <% end %>
    <% unless @person.twitter.blank? %>
      <li>
        <%= icon('twitter') %>
        <%= link_to @person.twitter, "http://twitter.com/" + @person.twitter %>
      </li>
    <% end %>
    <% unless @person.facebook.blank? %>
      <li>
        <%= icon('facebook') %>
        <%= link_to @person.facebook.gsub(/^.*facebook.com\//, ''), "http://facebook.com/#{@person.facebook}" %>
      </li>
    <% end %>
    <% unless @person.linkedin.blank? %>
      <li>
        <%= icon('linkedin') %>
        <%= link_to @person.nickname, "http://www.linkedin.com/profile/view?id=#{@person.linkedin}"%>
      </li>
    <% end %>
    <% unless @person.birthday.blank? %>
      <li title=<%= "#{format_date(@person.birthday)}" %>>
        <%= icon('gift') %>
        <%= "#{@person.birthday.day} #{t('date.month_names')[@person.birthday.month]}"%> (<%= t :age, count: @person.age %>)
      </li>
    <% end %>
  </ul>
  <%= call_hook(:view_persons_sidebar_attributes_bottom) %>
</div>

app/views/people/_list_excerpt.html.erb
<%= form_tag({}) do -%>
  <%= hidden_field_tag 'back_url', url_for(params) %>
  <%= hidden_field_tag 'project_id', @project.id if @project %>
  <div class="people">
    <%= render @people %>
  </div>
<% end %>
<div style="clear: both;"></div>
<p class="pagination"><%= pagination_links_full @people_pages, @people_count %></p>

app/views/people/_person.html.erb
<div class="vcard">
  <div class="avatar">
    <%= gravatar(person.email.to_s.downcase, :size => "100", :default => 'wavatar') unless person.email.blank? %>
    <!-- <%= avatar(person, :size => "200", :height => 200, :width => 200) %> -->
  </div>
  <div class="info">
    <p class="full_name"><%= link_to "#{person.first_name} #{person.last_name}", person_path(person) %></p>
    <p class="title"><%= person.job_title || "n/a" %></p>
  </div>
  <ul class="contacts">
    <% unless person.mobile_phone.blank? %>
      <li>
        <%= icon("phone") %>
        <%= truncate(person.mobile_phone, :length => 17) %>
      </li>
    <% end %>
    <% unless person.email.blank? %>
      <li>
        <%= icon("envelope") %>
        <%= mail_to truncate(person.email, :length => 30) %>
      </li>
    <% end %>
    <% unless person.skype.blank? %>
      <li>
        <%= icon("skype") %>
        <%= link_to truncate(person.skype, :length => 30), "skype:#{person.skype}?call" %>
      </li>
    <% end %>
    <% unless person.twitter.blank? %>
      <li>
        <%= icon("twitter") %>
        <%= link_to truncate(person.twitter, :length => 30), "http://twitter.com/" + person.twitter %>
      </li>
    <% end %>
    <% unless person.facebook.blank? %>
      <li>
        <%= icon("facebook") %>
        <%= link_to truncate(person.facebook.gsub(/^.*facebook.com\//, ''), :length => 30), "http://facebook.com/#{person.facebook}" %>
      </li>
    <% end %>
    <% unless person.linkedin.blank? %>
      <li>
        <%= icon("linkedin") %>
        <%= link_to truncate(person.nickname, :length => 30), "http://www.linkedin.com/profile/view?id=#{person.linkedin}"%>
      </li>
    <% end %>
  </ul>
</div>

app/views/people/_person_birthday.html.erb
<table class="person_data" id="person_birthday_<%= person_birthday.id %>">
  <tr>
    <td class="avatar"><%= link_to avatar(person_birthday, :size => "32"), person_path(person_birthday), :id => "avatar" %></td>
    <td class="name">
      <h4 class="contacts_header">
        <%= link_to person_birthday.nickname, person_path(person_birthday) %>
      </h4>
      <p>
          <span class="birthday bday" title=<%= "#{format_date(person_birthday.birthday)}" %>><%= birthday_date(person_birthday) %></span>

      </p>
    </td>
  </tr>
</table>

app/views/people/_projects.html.erb
<% unless @memberships.empty? %>
<ul>
<% for membership in @memberships %>
  <li><%= link_to_project(membership.project) %>
    (<%=h membership.roles.sort.collect(&:to_s).join(', ') %>, <%= format_date(membership.created_on) %>)</li>
<% end %>
</ul>
<% end %>
</div>

app/views/people/context_menu.html.erb
<ul>

	<% if @person.present? %>
		<li><%= context_menu_link l(:button_edit), {:controller => 'people', :action => 'edit', :id => @person}, :class => 'icon-edit', :disabled => !@can[:edit] %></li>
    <li><%= context_menu_link l(:button_delete), {:controller => 'people', :action => 'destroy', :id => @person}, :method => :delete, :data => {:confirm => @can[:delete] && l(:text_people_destroy_confirmation)}, :class => 'icon-del', :disabled => !@can[:delete] %></li>
	<% else %>
    <!-- <li><%# context_menu_link l(:button_edit), {:controller => 'people', :action => 'bulk_edit', :ids => @persons.collect(&:id)},
            :class => 'icon-edit', :disabled => !@can[:edit] %></li> -->
    <li><%= context_menu_link l(:button_delete), {:controller => 'people', :action => 'bulk_destroy', :ids => @people.collect(&:id)}, :method => :delete, :data => {:confirm => @can[:delete] && l(:text_people_destroy_confirmation)}, :class => 'icon-del', :disabled => !@can[:delete] %></li>
	<% end %>

</ul>

app/views/people/edit.html.erb
<div class="contextual">
    <%= link_to(l(:button_people_edit_profile), edit_user_path(@person.user), :class => 'icon icon-edit') if @person.user && User.current.admin? %>
</div>

<h2><%= l(:label_people_edit_person) %></h2>

<%= labelled_form_for :person, @person,
                             :url => {:action => 'update', :id => @person},
                             :html => { :multipart => true, :method => :put, :id => "person_form" } do |f|  %>
  <%= error_messages_for 'person' %>

  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_save) -%>
<% end -%>

<% content_for :sidebar do %>
<% end %>

<% content_for :header_tags do %>
  <%= javascript_include_tag :persons, 'jquery.tokeninput.js', 'person-token-input.js', :plugin => 'redmine_contractors'  %>
  <%= stylesheet_link_tag :persons, 'token-input.css', 'token-input-facebook.css', :plugin => 'redmine_contractors' %>
  <%= robot_exclusion_tag %>
<% end %>

app/views/people/show.html.erb
<%= error_messages_for 'person' %>

<% html_title "#{l(:label_people_person)} ##{@person.id}: #{@person.nickname}" %>

<div class="contextual">
  <%= icon('user') %>
  <%= link_to l(:label_profile), user_path(@person.user) if @person.internal? && @person.user %>
  <%= icon('edit') %>
  <%= link_to l(:button_edit), {:controller => 'people', :action => 'edit', :id => @person} if User.current.allowed_people_to?(:edit_people, @person) %>
  <%= icon('trash') if authorize_for('users', 'destroy') %>
  <%= link_to_if_authorized l(:button_delete), {:controller => 'users', :action => 'destroy', :project_id => @project, :id => @person}, :confirm => l(:text_are_you_sure), :method => :delete %>
</div>

<h2><%= l(:label_people_person) %> #<%= @person.id %></h2>
<div class="person_details">
  <table class="subject_header">
    <tr>
      <td class="avatar"><%= link_to avatar(@person, :size => "64", :full_size => true), @person.avatar %></td>
      <td class="name" style="vertical-align: top;">
        <h1><%= h @person.nickname %></h1>
        <p>
          <%= textilizable @person, :background, :attachments => @person.attachments %>
        </p>
        <p>
        <%= h @person.job_title %>
        </p>

      </td>
      <td class="subject_info">
        <ul>
          <% if @person.mobile_phones.any? %>
            <li class="phone icon icon-phone"><%= @person.mobile_phones.first %></li>
          <% end %>
          <li class="email icon icon-email"><%= mail_to @person.email %></li>
        </ul>
      </td>
    </tr>
  </table>

  <%= call_hook(:view_people_show_details_bottom, :person => @person) %>
</div>



<% person_tabs = [#{:name => 'activity', :partial => 'activity', :label => :label_activity},
        {:name => 'files', :partial => 'attachments', :label => :label_attachment_plural},
        {:name => 'projects', :partial => 'projects', :label => :label_project_plural}
        ] if @person.internal? %>

<%= render_tabs (person_tabs || []) %>


<% content_for :sidebar do %>
  <%= render :partial => 'attributes' %>
  <%= call_hook(:view_people_sidebar_after_attributes, :person => @person) %>
  <% if !@person.background.blank? %>
    <h3><%= l(:field_people_background) %></h3>
    <div class="wiki"><%= textilizable(@person, :background) %></div>
  <% end %>
<% other_formats_links do |f| %>
  <%= f.link_to 'VCF', :url => params %>
<% end %>
<% end %>



<% content_for :header_tags do %>
  <%= javascript_include_tag :persons, :plugin => 'redmine_contractors'  %>
  <%= stylesheet_link_tag :persons, :plugin => 'redmine_contractors' %>
<% end %>